### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by serge2016** [aakechin/BRCA-analyzer#1]
Hello!

I'd like to see, how you generate the Docker Image. Could you add the Dockerfile to this repo, please?

On the https://hub.docker.com/r/aakechin/brca-analyzer it is not available :(

**Comment by aakechin** [comment]
@serge2016, thank for your comment. You cannot download docker image, can you? What docker says you, if you use commands written in the manual?

**Comment by serge2016** [comment]
@aakechin No, I am interested in the Dockerfile itself.

**Comment by aakechin** [comment]
@serge2016, sorry that I didn't understand your question correctly. I added Dockerfile to the repository. Hope it will still be useful for you.
