### ISSUE TITLE
Update to GATK4?

### ISSUE THREAD

**Issue by serge2016** [aakechin/BRCA-analyzer#2]
Hi!
Why not to use GATK4? Starting with GATK4 it is fully open-source under a BSD 3-clause license: https://software.broadinstitute.org/gatk/documentation/article?id=11025

https://github.com/aakechin/BRCA-analyzer/blob/720b58d57fd88df5da266b503aa033f4b12380ea/install.py#L13

**Comment by aakechin** [comment]
@serge2016, thank you for your comment. Unfortunately, newer does not mean better. New version of GATK does not contain UnifiedGenotyper, and by our results it is better than HaplotypeCaller and other GATK commands.
