### ISSUE TITLE
ClinVar version

### ISSUE THREAD

**Issue by serge2016** [aakechin/BRCA-analyzer#3]
Hi!
In your script there is a `clinvar_20160831.vcf.gz`:
https://github.com/aakechin/BRCA-analyzer/blob/720b58d57fd88df5da266b503aa033f4b12380ea/brca_analyzer.py#L128.

Current version is `clinvar_20190513.vcf.gz`: ftp://ftp.ncbi.nlm.nih.gov/pub/clinvar/vcf_GRCh37/clinvar_20190513.vcf.gz. I suppose, it is important to update it...

**Comment by aakechin** [comment]
@serge2016, thank you for your comment! Unfortunately, now BRCA-analyzer does not have an opportunity to automatically update databases used. I suppose it will be done later. They are updated sometimes but not always because it is too time-consuming. You can update it for your personal use.
