### ISSUE TITLE
Evaluating uniformity of coverage

### ISSUE THREAD

**Issue by Oliversinn** [aakechin/BRCA-analyzer#4]
I'm getting the following error everytime:
Evaluating uniformity of coverage...
Traceback (most recent call last):
  File "brca_analyzer.py", line 448, in <module>
    '-lang '+args.lang,shell=True,stderr=sp.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python3 /brca_analyzer/drawUniformityFigure.py -cov muestras/BRCA_amplicon_coverage_mean.xls -out muestras/BRCA_amplicon_coverage_mean.uniformity.tiff -lang english' returned non-zero exit status 1

Any idea on how to fix it?

**Comment by Oliversinn** [comment]
And one other question, how do i prepare the patientable, do you have any example? I have 2 Pools per patient, that means that i have 4 files per patient. How should i call the analyzer in order to analyze both pools for each patient (extra: with the patientable)?

**Comment by aakechin** [comment]
@Oliversinn thank you for your questions! 

About the first question. Could you please call the command that led to the error and give me the output? So, please, call the command "python3 /brca_analyzer/drawUniformityFigure.py -cov muestras/BRCA_amplicon_coverage_mean.xls -out muestras/BRCA_amplicon_coverage_mean.uniformity.tiff -lang english" and write its output here.

About the second question. I've uploaded to the example directory example_patient_table.csv file. Index1 and Index2 columns are optional. They are only added as information to the output file, so they can be empty. Numbers from the 1st column should correspond to the numbers in the names of FASTQ-files.

Do you want to analyze them like one sample or like two different samples? If the first, you need to join R1 FASTQ-reads into one file and R2 FASTQ-reads to another one. If the second, give them different numbers in the 1st column and similar names in the 2nd one. And check that numbers from the 1st column correspond to the numbers of the FASTQ-files.

**Comment by Oliversinn** [comment]
This is the output im getting.

/brca_analyzer# python3 drawUniformityFigure.py -cov muestras/BRCA_amplicon_coverage_mean.xls -out muestras/BRCA_amplicon_coverage_mean.uniformity.tiff -lang english
[3508.38, 3856.722, 5957.45, 2535.64, 1816.29, 263.51, 2757.29, 2238.27, 2727.06, 916.58, 2463.24, 7486.71, 7435.8, 3653.11, 3582.14, 1044.85, 4888.78, 10257.27, 3179.1, 6680.85, 8194.94, 7972.481, 7747.39, 847.84, 5624.22, 8041.0, 11618.99, 6166.84, 7420.16, 4922.91, 2865.58, 4725.51, 7165.75, 8382.79, 8021.94, 7413.39, 10588.05, 9305.49, 5820.71, 8146.97, 10549.91, 13202.55, 12485.84, 11043.26, 10712.76, 8609.66, 6277.53, 6720.04, 5265.83, 6146.03, 6714.06, 9428.93, 7708.54, 3312.52, 5209.94, 7118.28, 7274.17, 6466.1, 5020.86, 5148.71, 1479.29, 4493.3, 4742.69, 8546.33, 2980.62, 5482.68, 1080.14, 5681.92, 2939.43, 3518.01, 3434.66, 4946.436, 4037.18, 4651.43, 2117.09, 4107.03, 7354.94, 6317.75, 6450.98, 5960.68, 9157.69, 7163.47, 3670.69, 7539.08, 9773.13, 8859.931, 5685.15, 5659.95, 7448.88, 10927.16, 9876.12, 9586.75, 10857.61, 8738.63, 8756.46, 4472.84, 5265.91, 8684.67, 7329.02, 9322.54, 7641.43, 7377.09, 7483.42, 6964.43, 8296.82, 6444.67, 5195.18, 6090.75, 8268.36, 9304.8, 9585.62, 10951.22, 9216.87, 8612.69, 6874.21, 7600.4, 7538.99, 9201.59, 6585.46, 6207.15, 8387.2, 7528.96, 8538.76, 10613.85, 8838.41, 8151.41, 8486.6, 7377.48, 8210.33, 11375.7, 10863.82, 8474.17, 7052.01, 6788.89, 6757.33, 7337.77, 5755.09, 8105.54, 7716.68, 5458.05, 4423.78, 3287.49, 1796.65, 3092.7, 4046.34, 5542.3, 1961.57, 3888.25, 6208.06, 6451.87, 5027.17, 5056.25, 6978.81, 6989.49, 9314.71, 8060.57, 4978.22, 6515.43, 6061.2, 3747.89, 5121.5, 3105.39, 4393.92, 5024.36, 6009.41, 7409.99, 4195.57, 1937.22, 769.79, 8255.55, 9964.93, 6996.92, 8896.71, 8022.12, 4852.49, 6588.42, 4575.01, 6113.32, 7320.17, 9192.25, 10787.88, 5666.78, 7419.14, 4868.31, 6540.02, 6535.97, 6274.27, 5651.76, 5757.86, 4979.98, 0.0, 0.0, 0.0]
[[  3508.38    3856.722   5957.45    2535.64    1816.29     263.51
    2757.29    2238.27    2727.06     916.58    2463.24    7486.71    7435.8
    3653.11    3582.14    1044.85    4888.78   10257.27    3179.1     6680.85
    8194.94    7972.481   7747.39     847.84    5624.22    8041.     11618.99
    6166.84    7420.16    4922.91    2865.58    4725.51    7165.75
    8382.79    8021.94    7413.39   10588.05    9305.49    5820.71
    8146.97   10549.91   13202.55   12485.84   11043.26   10712.76
    8609.66    6277.53    6720.04    5265.83    6146.03    6714.06
    9428.93    7708.54    3312.52    5209.94    7118.28    7274.17    6466.1
    5020.86    5148.71    1479.29    4493.3     4742.69    8546.33
    2980.62    5482.68    1080.14    5681.92    2939.43    3518.01
    3434.66    4946.436   4037.18    4651.43    2117.09    4107.03
    7354.94    6317.75    6450.98    5960.68    9157.69    7163.47
    3670.69    7539.08    9773.13    8859.931   5685.15    5659.95
    7448.88   10927.16    9876.12    9586.75   10857.61    8738.63
    8756.46    4472.84    5265.91    8684.67    7329.02    9322.54
    7641.43    7377.09    7483.42    6964.43    8296.82    6444.67
    5195.18    6090.75    8268.36    9304.8     9585.62   10951.22
    9216.87    8612.69    6874.21    7600.4     7538.99    9201.59
    6585.46    6207.15    8387.2     7528.96    8538.76   10613.85
    8838.41    8151.41    8486.6     7377.48    8210.33   11375.7    10863.82
    8474.17    7052.01    6788.89    6757.33    7337.77    5755.09
    8105.54    7716.68    5458.05    4423.78    3287.49    1796.65    3092.7
    4046.34    5542.3     1961.57    3888.25    6208.06    6451.87
    5027.17    5056.25    6978.81    6989.49    9314.71    8060.57
    4978.22    6515.43    6061.2     3747.89    5121.5     3105.39
    4393.92    5024.36    6009.41    7409.99    4195.57    1937.22
     769.79    8255.55    9964.93    6996.92    8896.71    8022.12
    4852.49    6588.42    4575.01    6113.32    7320.17    9192.25
   10787.88    5666.78    7419.14    4868.31    6540.02    6535.97
    6274.27    5651.76    5757.86    4979.98       0.         0.         0.   ]]
(1, 193)
Traceback (most recent call last):
  File "drawUniformityFigure.py", line 57, in <module>
    cvs.append(round(float(stat.stdev(data[:,j])/stat.mean(data[:,j])),3))
  File "/usr/lib/python3.5/statistics.py", line 617, in stdev
    var = variance(data, xbar)
  File "/usr/lib/python3.5/statistics.py", line 555, in variance
    raise StatisticsError('variance requires at least two data points')
statistics.StatisticsError: variance requires at least two data points

**Comment by aakechin** [comment]
@Oliversinn thank you! I've found the bug. It occurred because you analyzed only one sample. Could you please download updated file drawUniformityFigure.py and upload it to your docker container to the directory /brca_analyzer/? It should work now.

**Comment by Oliversinn** [comment]
It's working now!!! :) Thank you for the help, thank you for the analyzer.

**Comment by Oliversinn** [comment]
Just one last thing. This is about the patient table. My fastq file is name BR110_S11_L001_R1_001.fastq.gz so what should i type on the Patient_Num? Right now this is my patient_table.csv:

Patient_Num     Patient_ID      Index1  Index2
1       BR110

But i'm having this error:

Adding positions in old references...
ERROR: Some problems with reading patient table file!
<class 'IndexError'>

**Comment by aakechin** [comment]
@Oliversinn If you have not so many FASTQ-files, it would be better for the analyzer, if you could rename your FASTQ-files in the following format: <patient_num>_S<patient_num>_L001_R1_001.fastq.gz, e.g. 1_S1_L001_R1_001.fastq.gz. In this case the analyzer will recognize patient numbers more likely. I think you have such an error, because patient table should have tabulation (\t) as a column separator

**Comment by Oliversinn** [comment]
I still trying but i cant get it. This is the command and the output:

root@118e28f9dabd:/brca_analyzer# python3 brca_analyzer.py -r1 'muestras/1_S1_L001_R1_001.fastq.gz' -pat 'patient_table.csv' -out muestras/ -th 2 -tt 4
Process reads...
100.0%
Done
Joining mutations of all patients...
Done
Annotating mutations of all patients with ANNOVAR...
Done
Adding positions in old references...
ERROR: Some problems with reading patient table file!
<class 'IndexError'>

And this is my patient_table.csv

Patient_Num     Patient_ID      Index1  Index2
1       BR110   000     000
(it is tabbed)

**Comment by aakechin** [comment]
@Oliversinn I think the ploblem might be with the empty string in your file? You can download updated scripts addPosOldRef.py, countCovForAmplic.py, and getPercentOfProperlyTrimmedReads.py from the repository. It should work, if this was the ploblem. And check, if the last string of your file is empty.

**Comment by Oliversinn** [comment]
I made the changes you suggest, but now another problem came out.

python3 brca_analyzer.py -r1 'muestras/1_S1_L001_R1_001.fastq.gz' -pat 'patient_table.csv' -out muestras/ -th 2 -tt 4
Process reads...
100.0%
Done
Joining mutations of all patients...
Done
Annotating mutations of all patients with ANNOVAR...
Done
Adding positions in old references...
Traceback (most recent call last):
  File "brca_analyzer.py", line 360, in <module>
    output=sp.check_output("python3 "+thisDir+"addPosOldRef.py -in "+outDir+'allPatients.unifiedGenotyper.ann.avinput.ann.hg19_multianno.txt -pt '+patientsTable+' -pl '+'_'.join(patNums),shell=True,stderr=sp.STDOUT)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 708, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'python3 /brca_analyzer/addPosOldRef.py -in muestras/allPatients.unifiedGenotyper.ann.avinput.ann.hg19_multianno.txt -pt /brca_analyzer/patient_table.csv -pl 1' returned non-zero exit status 1
